### ISSUE TITLE
Invalid list items in HTML export

### ISSUE THREAD

**Issue by pawelszramowski** [WikidPad/WikidPad#35]
List items start with a self closing tag (`<li class="wikidpad" />`content) instead of having both starting and closing tags (`<li class="wikidpad">`content`</li>`). Such lists are correctly displayed by a web browser (I tried Mozilla Firefox), but fail W3C validation and are - most importantly - ignored by applications which import HTML (I tried pandoc, Evernote, CherryTree). That makes the HTML export feature rather useless.

I tried to fix that in `extensions/HtmlExporter.py`, but came to a conclusion that it's not so simple and requires changing how list items are represented in AST.

WikidPad 2.3rc01 on Windows 10.

**Comment by vashnt707** [comment]
This fixes the said bug but after this in edit mode WikiWords aren't getting highlighted with blue link. I have my own parser with few tweaks such as the WikiWord has double brackets. These aren't getting highlighted with blue link in edit mode. However on double clicking it does open the corresponding WikiWord and the HTML preview also works fine.

    * [[MyPrimaryRecipe]]
    * [[MyIngredientList]]

The above WikiWords aren't getting highlighted with blue link.

The AST differs from now to previous working version by the only difference that all the items are pushed down one level inside bulletEntry under unorderedList

Let me know how do I debug further or if you could think of the root cause.

**Comment by butscher** [comment]
@vashnt707 Thanks. Newest commit fixes this.
