### ISSUE TITLE
Is WikidPad still maintained? Future plans?

### ISSUE THREAD

**Issue by BjornFJohansson** [WikidPad/WikidPad#69]
Hi, Just wanting to ask if the plan is still to maintain WikidPad?
Last changes to the master branch was in 2019.
I am still an avid user, 5997 pages so far.

**Comment by gchriz** [comment]
On 13.01.21 at 12:45 Björn Johansson wrote:
> Hi, Just wanting to ask if the plan is still to maintain WikidPad?
> Last changes to the master branch was in 2019.

Good question. I'm eager to know that as well.

On my current Linux systems (Fedora 33) WikidPad doesn't run any more.
Neither the current Python2 version nor the Alpha-version for Python3.

And I'm not sure if it's realistic waiting for the Python3 version of
WikidPad to mature.

Unfortunately the code migration is way over my own capabilities.


> I am still an avid user, 5997 pages so far.
Wow!
I don't have so many, but several Wikis spread all over the topics/systems.

So I'm exploring alternatives to WikidPad now. To be able to work with
all those files in the meantime...

Not so easy since the features of WikidPad are still amazing.


Christian

**Comment by vashnt707** [comment]
I use WikidPad in windows (although with a lot of customization to make it work in a stable manner), I occasionally test the changes in Linux and Mac. Last couple of years I have seen increasingly more issues in Linux and Mac especially with GUI events, Browser backends and some unknown wx bugs in Mac. With IE11 out of windows and Phoenix recommending Edge with custom wxWidgets build, I don't think its going to be easy to maintain let alone update.

If someone strong in WxPython puts a decent effort to update to latest 4.1 with browser updates, this should last another 5-8 years.

**Comment by BjornFJohansson** [comment]
@gchriz Stay with wikidpad! I run wikidpad on python 3.9 with wxPython 4.1.0
Works like a charm except for the spell checking. I run from source using anaconda which I recommend.
Let me know if you are interested, I maintain a forked repository with an extra branch with an unofficial updated version.

**Comment by gchriz** [comment]
On 22.01.21 at 11:13 Björn Johansson wrote:

> @gchriz Stay with wikidpad! I run wikidpad on python 3.9 with
> wxPython 4.1.0 Works like a charm except for the spell checking. I
> run from source using anaconda which I recommend. Let me know if you
> are interested.

Yes, I am interested!!!


Here on Fedora it's Python 3.9.1 with wxPython 4.0.7.
So it might work...

I have only little experience with anaconda yet. But willing to learn.


My other plan has been to try building a virtualenv and/or a Flatpak
with the Python2 version of WikidPad as a workaround.

But if it's possible to get the new version running would be really
appreciated!


Christian

**Comment by cknoll** [comment]
I am also highly interested in a sustainable future of Wikidpad (2700 pages) currently I am running 2.3rc02 from source on debian10 (with python2.7) it mostly works for now, except some shortcut keys. I think it would be great to have a mature version which could painlessly be installed via `pip install wikidpad`.

**Comment by cknoll** [comment]
In fact, I think it is time to be a bit more ambitious:


## Wikidpad Sustainability


First of all, I owe wikidpad a huge deal of my current life quality. I
probably would not have finished my PhD without this tool and maybe I
would have gone crazy due to information overload. So, dear Michael, and
all other contributors thank you very much for providing this great tool to
the world. It deserves way more attention!

My wiki has several 1000 pages and keeps growing. This means I heavily
depend on it. I hope to use wikidpad over the next five years or
probably much longer.

Recently I was affected by https://github.com/WikidPad/WikidPad/issues/61.
Wikidpad did not start at all. Luckily, I had some time to fix that, but
there are days on which such an incident would cause serious trouble.
While figuring out the background of this problem I realized that the
project activity currently is quite low:
- Latest News on http://wikidpad.sourceforge.net/: release of 2.3rc2 from 2018-11,
- several open pull requests, with now or low discussion activity,
- several open issues...

I have the fear that I soon might depend on some orphaned software and I
have a quite strong incentive to prevent this. I totally understand that
maintaining a free software project consumes a lot of time and mental
energy and that there are a lot of other activities in life which are
much more important and probably more fulfilling. In fact I am a strong
advocate that free software needs sustainable funding <off-topic> See [my
activities](http://fsfw-dresden.de/funding-foss) in this regard </off-topic>! So, to be very clear on
that: this message is not meant as criticism. I is an attempt to support
wikidpad, such that it continues to be useful for its current and
probably many future users.

I suggest the following:

- Consider to publish version 2.3 as stable version

- Close old issues (e.g. like
https://github.com/WikidPad/WikidPad/issues/13) and pull requests.
Encourage initial authors to open a new one if they think it is appropriate.

- Update the website an point to the github repo

- Deprecate sourceforge. It has IMHO a bad reputation and seems
redundant to github. And it seems to not support https which leads to
"unsafe-warnings" in some browsers.

- Consider to move the wiki from http://trac.wikidpad2.webfactional.com/
(last change 2015) to github (or completely drop it)

- Consider to include docs in the project repo and ship the on
https://readthedocs.org/ automatically (with web hooks)

- Reduce the amount of branches (currently 22)

- Make wikidpad installable via pip

- Complete the port to python3 (maybe drop python2 support for that)

- Introduce continuous integration (travis, drone.io, ...)


Obviously these actions would take quite a lot of work, most of which is
rather boring but nevertheless important. It would be unfair and
unrealistic to expect the maintainer to accept such a task list from
some random dude like me and euphorically start to work. Instead I
suggest the following:

- Gather people who are interested in keeping wikidpad acitve (and
improving). E.g. by contacting all people who have starred or forked the
repo.

- Collect reliable pledges from these people (E.g. "I will contribute at
least 5 hours of work until 2021-03-31" or "I will provide 10 Euro for
each milestone reached")

- Consider to use external freelancers to do some of the boring stuff
(via Upwork, fiverr, bountysource)

Obviously, I by myself am willing to pledge something: 50 Euro without any
condition, and 50 Euro more if togehter we reach at least 1000 Euro
until 2021-03-31. Additionally, I pledge at least 3 hours until
2021-03-31. In the future until 2025 I pledge at least 25 Euro per year,
in which at least one stable release happens, for general development
and more for specific features like Markdown support
(which I would love to have).


Let me close again with a huge thank to Michael and all other
contributors. Free Software is an amazing civilizing achievement and it
feels very satisfying to be part of that.

**Comment by ravbag** [comment]
> @gchriz Stay with wikidpad! I run wikidpad on python 3.9 with wxPython 4.1.0
> Works like a charm except for the spell checking. I run from source using anaconda which I recommend.
> Let me know if you are interested, I maintain a forked repository with an extra branch with an unofficial updated version.

I would love to be able to run this via anaconda. I still have Python2 set as default on my system because of WikidPad. I just can't let go

**Comment by ravbag** [comment]
> In fact, I think it is time to be a bit more ambitious:
> ## Wikidpad Sustainability
Those are all great points Carsten and I am completely with you, including the PhD part. I might still have gotten a PhD without WP but it probably saved me a lot of time and gray hair.

I also saw your slides regarding FLOSS, where the quote by Hans Scholl struck me. We all need to do something. I can do some terrible Python and test on Linux systems, if that would help. 
Regarding the money part, I have donated before out of gratitude and guilt but it's not really a sustainable model. The amount of money needed to properly pay someone for their time is probably way more than what we could rustle up. 

However, if it helps, I would be up for a voluntary subscription kind of a thing where we commit to regular donation, for me 25€ p.a. would be fine.

More than money, it's gratitude that I have for everyone involved with WikidPad and FLOSS  is everything that's beautiful about Humanity, sharing, caring, gifting and creativity.

**Comment by Jens-G** [comment]
+1 fully agree. Just wan't to let you know you have plenty of happy users out there.

**Comment by cknoll** [comment]
One thing, which might be helpful for moving Wikidpad forward would be at least one person with some time *and* write access to the official repo. As I can overlook the situation: currently the Wikidpad Organization has three members (@butscher @matysek @gchriz), but this does not mean, that all of them have write access.

Does anyone know more?

**Comment by matysek** [comment]
@cknoll and others if you want to maintain wikidpad and form a new dev team, just let me know for a write access. I was using wikidpad in the past.

**Comment by gchriz** [comment]
All of us (@butscher @matysek @gchriz), have write access.
So it should be easy to extend the dev team.

I really hope that Michael will become active again, at least somehow...
He is still the main developer.

**Comment by BjornFJohansson** [comment]
Hi all, I will try to package my latest code into a setuptools package and a conda package. 
I am busy right now, but in the end of next week I will have some time for this I hope.
I will post here when it is ready. Ill need help with testing on windows and hopefully on Mac.

**Comment by matysek** [comment]
@BjornFJohansson @cknoll you should now have write access to the mater repo. If you need anything else let me know.

**Comment by spicedreams** [comment]
I am also a longterm WikidPad user, formerly Windows now Linux only (but with Android machines able to see the .wiki files too). My main wiki has 12615 pages using original_sqlite, and has been on WikidPad 2.3beta16 since it came out (previously on versions down to 1.x). I use WikidPad every day, and like others I have made donations in the past but recognise it's not a sustainable model.
I came here to ask about something trivial, and saw that there had been no updates for more than two years and thought, that's rather wonderful, code that is so functional and so stable it has not needed a change in over 2 years! It is a great testament to Michael's work and others who have contributed.  

I think we all need a way to continue using WikidPad despite drift in the operating system environments. That is a tough ask, but there are various 'solutions' like virtualenv and particularly, docker might work for many people. I'm sure it could be made to work with pip or Anaconda, but that would restrict its appeal to people who can tangle with those development tools.  

My biggest regret with WikidPad is that it is single-user. I know you can sort of work around this by sharing the .wiki files but having your own sqlite database, but it's asking for trouble if less technical people are working on more or less the same part of the system.

**Comment by BjornFJohansson** [comment]
@spicedreams I agree. I have 6103 pages as of today and I do not see how I could stop using it. The social part is a drawback. I have toyed with ideas to make an export function that could make an online wiki by translating to the github wiki format or modify a wiki frontend to accept the wikidpad syntax.

**Comment by Jens-G** [comment]
Just to bring this on the table again: It does not run under LMDE "Elsie" anymore. 
 * The py2 version lacks the wx package - seems not available anymore via official package sources 
 * the py3 version fails with that [infamous "Syntax error"](https://groups.google.com/g/wikidpad-devel/c/WHQUdBTVnTU)

**Comment by BjornFJohansson** [comment]
@Jens-G That seems a Python2 / Python3 thing? I run python on Python 3 every day and it works fine.
I do think the default version should be a pypi package to make it easier to maintain. I have done some maintenance
in the past, but I got stuck in the spell check, never got it to work.
